[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38', 'py39', 'py310', 'py311']

[tool.isort]
profile = "black"
line_length = 88
known_third_party = [
    "anyio", "black", "build", "certifi", "charset-normalizer", "click", "dnspython", "duckdb", 
    "email_validator", "exceptiongroup", "fastapi", "fastapi-cli", "gensim", "h11", "httpcore", 
    "httptools", "httpx", "idna", "iniconfig", "isort", "Jinja2", "joblib", "markdown-it-py", 
    "MarkupSafe", "mdurl", "mypy-extensions", "nltk", "numpy", "packaging", "pathspec", "platformdirs", 
    "pluggy", "pydantic", "pydantic_core", "Pygments", "pyproject_hooks", "pytest", "pytest-mock", 
    "python-dotenv", "python-multipart", "PyYAML", "regex", "requests", "rich", "scipy", "shellingham", 
    "smart-open", "sniffio", "starlette", "tomli", "tqdm", "typer", "typing_extensions", "urllib3", 
    "uvicorn", "uvloop", "watchfiles", "websockets", "wrapt"
]
