name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    name: Lint and isort
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip setuptools wheel
          pip install -r requirements.txt

      - name: Run black (linter)
        run: |
          . .venv/bin/activate
          make lint

      - name: Run isort
        run: |
          . .venv/bin/activate
          make isort

  test:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip setuptools wheel
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          . .venv/bin/activate
          make test
